export const ActionTypes = {
  POST_DOG: "POST_DOG",
  GET_ALL_DOGS: "GET_ALL_DOGS",
  GET_BY_BREED: "GET_BY_BREED",
  GET_TEMPERAMENTS: "GET_TEMPERAMENTS",
  ORDER_BY_ALPHABET: "ORDER_BY_ALPHABET",
  ORDER_BY_WEIGHT: "ORDER_BY_WEIGHT",
  FILTER_BY_TEMPERAMENT: "FILTER_BY_TEMPERAMENT",
  FILTER_BY_BREED: "FILTER_BY_BREED",
  FILTER_CREATED: "FILTER_CREATED",
  SEARCH_TEMPERAMENT: "SEARCH_TEMPERAMENT",
  SEARCH_BREED: "SEARCH_BREED",
  DETAILS: "DETAILS",
  CLEAN_DETAIL: "CLEAN_DETAIL",
  
};
